name: Build

on:
  push:
    branches: [ "master" ]

env:
  REPO_PATH: ${{ vars.REPO_PATH }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and restart
    - uses: actions/checkout@v4

    - name: Build
      run: echo ${{ vars.REPO_PATH }}
